import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Navbar from "./components/Navbar";

// components

const rubik = Rubik({ subsets: ["latin"] });

// This metadata will be used on every page (can override this on a page by page basis)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This essentially wraps any page component in the application. Whatever we put
// in layout.tsx will appear on every page (eg: Navbar)
// In case of nextjs, layout components wrap page components
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
